# This is a basic workflow to help you get started with Actions

name: Deploy
on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm install --production
      - run: npm install mup
      - run: ls      
      - run: cd .production
      - run: ls
      - run: npx mup deploy
      
